### ISSUE TITLE
" - " (Paprium) vs Wolverine (X-Men: Children of the Atom)

### ISSUE THREAD

**Issue by ghost** [ArcadeHustle/CSI-Paprium#17]
![image](https://user-images.githubusercontent.com/93481586/139752887-50554b29-9356-47e4-9111-e5e71d0e27ca.png)
![image](https://user-images.githubusercontent.com/93481586/139753109-4e5c2bf7-8d1d-4291-93b0-795fbd419ce2.png)

https://youtu.be/vlzEtLqcqWY?t=2719

**Comment by ArcadeHustle** [comment]
Wait, how is this "concept art", seems like a chicken / egg situation. Which came first?
![FDJa1AqX0AAMEII](https://user-images.githubusercontent.com/41961787/139759676-3920c868-f4f5-4116-8267-88fb7af89173.jpeg)
