### ISSUE TITLE
Dice (Paprium) vs Ruth (Crude Buster)

### ISSUE THREAD

**Issue by ghost** [ArcadeHustle/CSI-Paprium#23]
![image](https://user-images.githubusercontent.com/93481586/140171519-2d5f3a78-420b-4d6c-a38b-5438cc799258.png)

**Comment by ArcadeHustle** [comment]
player name is either "Ruth or his partner Sid" https://tvtropes.org/pmwiki/pmwiki.php/VideoGame/CrudeBuster
