### ISSUE TITLE
Murdock (Paprium) vs Duke (The King of Fighters 2000)

### ISSUE THREAD

**Issue by ghost** [ArcadeHustle/CSI-Paprium#8]
![image](https://user-images.githubusercontent.com/93481586/139599432-8158bcd0-5cd7-4c4d-ab25-fe7785b11d4a.png)

**Comment by ArcadeHustle** [comment]
![image](https://user-images.githubusercontent.com/41961787/140416049-ed2da7b8-4be2-440d-ac61-64854162f162.jpeg)
https://twitter.com/xluis__martinsx/status/1350580405859135490?lang=en
